export const Action = {
  SET_TODO: "SET_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  COPY_TODO: "COPY_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  //    Modal Reducer
  SET_MODAL: "SET_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  // Balance
  SET_MONEY: "SET_MONEY",
};
